### ISSUE TITLE
Is this script still being developed and supported

### ISSUE THREAD

**Issue by nootkan** [mccarthy/phpFormProtect#5]
Just wanted to try your script but see it hasn't been updated in a couple of years.  Are you still supporting this script?

**Comment by mccarthy** [comment]
Hi, I'm not sure what type of support you are expecting, but I'm happy to answer any questions you have.

**Comment by nootkan** [comment]
Great.  I was just wanting to know if this script is still compatible with php 5.6.40?

**Comment by mccarthy** [comment]
I almost certainly wrote this for PHP 5,  I can't say with certainty which version exactly though since it has been a number of years since I deployed this.  That said, it's not a very complex piece of software so even if it doesn't work on a given PHP version it shouldn't be hard to make it work.
